return {}
-- return {
--   "benlubas/molten-nvim",
--   version = "^1.0.0", -- use version <2.0.0 to avoid breaking changes
--   build = ":UpdateRemotePlugins",
--   init = function()
--     -- these are examples, not defaults. Please see the readme
--     vim.g.molten_image_provider = "image.nvim"
--     vim.g.molten_output_win_max_height = 20
--   end,
--   dependencies = {
--     {
--       "3rd/image.nvim",
--       build = false,
--       opts = {
--         backend = "sixel",
--         processor = "magick_cli",
--         integrations = {},
--         max_width = 100,
--         max_height = 12,
--         max_height_window_percentage = math.huge, -- this is necessary for a good experience
--         max_width_window_percentage = math.huge,
--         window_overlap_clear_enabled = true,
--         window_overlap_clear_ft_ignore = { "cmp_menu", "cmp_docs", "" },
--       },
--     },
--   },
--   keys = {
--     { "<Leader>m", desc = "Molten Commands" },
--     { "<Leader>mi", ":MoltenInit<CR>", desc = "Initialize Molten" },
--     { "<Leader>me", ":MoltenEvaluateOperator<CR>", desc = "Run operator selection" },
--     { "<Leader>ml", ":MoltenEvaluateLine<CR>", desc = "Evaluate line" },
--     { "<Leader>mm", ":MoltenReevaluateCell<CR>", desc = "Evaluate cell" },
--     { "<Leader>mv", ":MoltenEvaluateVisual<CR>", desc = "Evaluate visual selection" },
--     { "<Leader>md", ":MoltenDelete<CR>", desc = "Delete cell" },
--     { "<Leader>mh", ":MoltenHideOutput<CR>", desc = "Hide output" },
--     { "<Leader>mo", ":MoltenEnterOutput<CR>", desc = "Show/Enter output" },
--   },
-- }
-- return {
--   "imbue-ai/jupyter_ascending.vim",
--   build = {
--     "uv pip install jupyter_ascending",
--     "jupyter nbextension install --py --sys-prefix jupyter_ascending",
--     "jupyter nbextension     enable jupyter_ascending --sys-prefix --py",
--     "jupyter serverextension enable jupyter_ascending --sys-prefix --py",
--   },
--   keys = {
--     { "<Leader>jj", "<Plug>JupyterExecute" },
--     { "<Leader>ja", "<Plug>JupterExecuteAll" },
--     { "<Leader>jr", "<Plug>JupyterRestart" },
--   },
-- }
-- return {
--   "SUSTech-data/neopyter",
--   dependencies = {
--     "nvim-lua/plenary.nvim",
--     "nvim-treesitter/nvim-treesitter", -- neopyter don't depend on `nvim-treesitter`, but does depend on treesitter parser of python
--     "AbaoFromCUG/websocket.nvim", -- for mode='direct'
--   },
--   cond = function() return vim.api.nvim_buf_get_name(0):match ".ju.py$" ~= ".ju.py" end,
--   opts = {
--     mode = "direct",
--     remote_address = "127.0.0.1:9328",
--     file_pattern = { "*.ju.*" },
--     on_attach = function(buf)
--       local function map(mode, lhs, rhs, desc) vim.keymap.set(mode, lhs, rhs, { desc = desc, buffer = buf }) end
--       -- same, recommend the former
--       map("n", "<C-Enter>", "<cmd>Neopyter execute notebook:run-cell<cr>", "run selected")
--       -- map("n", "<C-Enter>", "<cmd>Neopyter run current<cr>", "run selected")
--
--       -- same, recommend the former
--       map("n", "<Leader>rr", "<cmd>Neopyter execute notebook:run-all-above<cr>", "run all above cell")
--       -- map("n", "<space>X", "<cmd>Neopyter run allAbove<cr>", "run all above cell")
--
--       -- same, recommend the former, but the latter is silent
--       map("n", "<space>rs", "<cmd>Neopyter execute kernelmenu:restart<cr>", "restart kernel")
--       -- map("n", "<space>nt", "<cmd>Neopyter kernel restart<cr>", "restart kernel")
--
--       map(
--         "n",
--         "<S-Enter>",
--         "<cmd>Neopyter execute notebook:run-cell-and-select-next<cr>",
--         "run selected and select next"
--       )
--       map(
--         "n",
--         "<M-Enter>",
--         "<cmd>Neopyter execute notebook:run-cell-and-insert-below<cr>",
--         "run selected and insert below"
--       )
--
--       map("n", "<F5>", "<cmd>Neopyter execute notebook:restart-run-all<cr>", "restart kernel and run all")
--     end,
--   },
-- }
